# Generated by Django 5.1.dev20240130154802 on 2024-01-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("campaign", models.TextField()),
                ("voice", models.TextField()),
                ("recognize", models.TextField()),
                ("inside", models.FloatField()),
                ("growth", models.TextField()),
                ("side", models.FloatField()),
                ("yard", models.TextField()),
                ("discussion", models.TextField()),
            ],
        ),
    ]
